### ISSUE TITLE
Value in wrong format is written to config on Windows with Russian localization

### ISSUE THREAD

**Issue by Gebcy** [the-database/VideoJaNai#12]
[error.log](https://github.com/the-database/AnimeJaNaiConverterGui/files/14627711/error.log)
(Version 0.0.9)

Config with incorrect values on Russian localization:
chain_1_rife_factor_numerator=5,0
chain_1_rife_factor_denominator=1,0
chain_1_rife_scene_detect_threshold=0,100

Config with correct values on English localization:
chain_1_rife_factor_numerator=5.0
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.10

I think this is due to regional differences in number formats. And this may happen not only with Russian localization, but also with all localizations that use a comma instead of a dot as a decimal separator.

**Comment by the-database** [comment]
Fixed in v1.0.0
