### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by Albidoten** [the-database/VideoJaNai#17]
it shows this
![Screenshot 2024-05-07 143201](https://github.com/the-database/AnimeJaNaiConverterGui/assets/159302410/56338845-9cac-4579-9722-23acb6f999b4)

**Comment by Albidoten** [comment]
> Update your NVIDIA driver to the latest version and try again.

i have intel integrated gpu that means it won't work for me

**Comment by the-database** [comment]
If you have Intel, change the Upscaling Backend from TensorRT to DirectML or NCNN. 

Also update the ONNX Model Path and select a model which is fp32.
