### ISSUE TITLE
Audio & Subtitles

### ISSUE THREAD

**Issue by card0z** [the-database/VideoJaNai#24]
Audio and subtitles are not there in the output. The options to choose from various audio tracks and subtitles are available. But they don't work.

**Comment by card0z** [comment]
The audio works when the file is opened from the beginning. If I scrub through the timeline, the audio stops working. The subtitles don't work properly from the beginning.

I have tried with multiple onxx models and it is the same with all. Maybe an ffmpeg problem?

**Comment by JanChec** [comment]
The same symptoms here, except that subtitles seem to work. Tried with PotPlayer and mpv, HEVC and x264. Short videos work well, but 20min+ ones don't - with HEVC I get only sound at the beginning & black video, with x264 sound + video at the beginning, but anywhere else it's silent.

**Comment by the-database** [comment]
Try adding this to the end of the ffmpeg settings: `-max_interleave_delta 0`

Like this for example:
![image](https://github.com/user-attachments/assets/778a4e7c-ca31-4559-b29d-57ca73345b01)

In the next update this setting will be applied automatically so you won't have to worry about it.

**Comment by JanChec** [comment]
It works, thanks! :)

**Comment by the-database** [comment]
Fixed in v1.0.0
