### ISSUE TITLE
Conversion Failed Report.

### ISSUE THREAD

**Issue by 2ji3150** [the-database/VideoJaNai#8]
[error.log](https://github.com/the-database/AnimeJaNaiConverterGui/files/14152067/error.log)

Item|Description
-|-
Model|2x_AnimeJaNai_HD_V3Sharp1_ESRGAN_110k-fp16.onnx
FFmpeg Presets|x264(CPU)
Rife|No
Resize|No
Backend|TensorRT
GPU|RTX4070
CPU|AMD Ryzen R5-7600x
RAM|DDR5 6000 16GB x 2
OS|Windows11 23H2 (22631.3085)
Nvidia Driver|551.23

***Note That with the `2x_AnimeJaNai_HD_V3_Sharp1_Compact_430k-fp16.onnx` model, it works properly.***

Related Issue #2

**Comment by 2ji3150** [comment]
[error.log](https://github.com/the-database/AnimeJaNaiConverterGui/files/14152159/error.log)

Item|Description
-|-
Model|2x_AnimeJaNai_HD_V3_Sharp1_Compact_430k-fp16.onnx
FFmpeg Presets|x264(CPU)
Rife|Yes
Resize|No
Backend|TensorRT
GPU|RTX4070
CPU|AMD Ryzen R5-7600x
RAM|DDR5 6000 16GB x 2
OS|Windows11 23H2 (22631.3085)
Nvidia Driver|551.23

**Comment by 2ji3150** [comment]
Another video as input without RIFE.
Use `2x_AnimeJaNai_HD_V3_Sharp1_Compact_430k-fp16.onnx` to do 4x and resize to 2160p
and the input video is av1 encoded.

[error.log](https://github.com/the-database/AnimeJaNaiConverterGui/files/14152214/error.log)


Item|Description
-|-
Model|2x_AnimeJaNai_HD_V3_Sharp1_Compact_430k-fp16.onnx
FFmpeg Presets|x265(CPU)
Rife|No
Resize|No
Backend|TensorRT
GPU|RTX4070
CPU|AMD Ryzen R5-7600x
RAM|DDR5 6000 16GB x 2
OS|Windows11 23H2 (22631.3085)
Nvidia Driver|551.23

**Comment by the-database** [comment]
These issues should all be fixed in v1.0.0, please open a new issue if you see any similar errors in v1.0.0.
